#!/bin/sh
# rebuild.sh (universal) — regenerate sing-box config from user servers in
# /etc/sing-box/servers/*.json. Nothing is hardcoded: with no servers the config is
# valid and routes DIRECT (VPN off, internet stays up); with servers it builds an
# urltest "auto" + a "select" selector over them. Validates with `sing-box check`,
# restarts the service, re-applies LAN forwarding. Prints OK or CHECK_FAIL.
#
# DNS uses the sing-box >=1.12 schema:
#   servers: [{ "type":"udp", "server":"8.8.8.8" }, ...]   (NOT the legacy "address")
#   route.default_domain_resolver -> a direct DNS, so that hostname server addresses
#   in outbounds can be resolved (FATAL to omit on 1.12+; this is the known bug fix).
SBDIR=${SBDIR:-/etc/sing-box}
SRVDIR="$SBDIR/servers"
CFG="$SBDIR/reality_full.json"
SB="$SBDIR/sing-box"
[ -x "$SB" ] || SB=$(command -v sing-box || echo "$SB")
mkdir -p "$SRVDIR"
SRV_OUT=""; SRV_TAGS=""; N=0
for f in "$SRVDIR"/*.json; do
  [ -f "$f" ] || continue
  t=$(basename "$f" .json)
  SRV_OUT="$SRV_OUT,
$(cat "$f")"
  SRV_TAGS="$SRV_TAGS,\"$t\""
  N=$((N+1))
done
cp -f "$CFG" "$CFG.bak" 2>/dev/null
if [ "$N" -eq 0 ]; then
  # no servers yet -> valid direct-only config so the router keeps internet
  OUTBOUNDS='{ "type": "direct", "tag": "direct" }'
  FINAL="direct"
else
  SRV_TAGS_CLEAN=${SRV_TAGS#,}
  OUTBOUNDS="${SRV_OUT#,},
    { \"type\": \"urltest\", \"tag\": \"auto\", \"outbounds\": [${SRV_TAGS_CLEAN}], \"url\": \"https://www.gstatic.com/generate_204\", \"interval\": \"30s\", \"tolerance\": 80 },
    { \"type\": \"selector\", \"tag\": \"select\", \"outbounds\": [\"auto\"${SRV_TAGS}], \"default\": \"auto\" },
    { \"type\": \"direct\", \"tag\": \"direct\" }"
  FINAL="select"
fi
cat > "$CFG" <<JSON
{
  "log": { "level": "warn", "timestamp": true },
  "experimental": { "clash_api": { "external_controller": "127.0.0.1:9090" } },
  "dns": {
    "servers": [
      { "tag": "remote", "type": "udp", "server": "8.8.8.8" },
      { "tag": "direct-dns", "type": "udp", "server": "1.1.1.1" }
    ],
    "final": "remote",
    "strategy": "prefer_ipv4"
  },
  "inbounds": [
    { "type": "tun", "tag": "tun-in", "interface_name": "singtun0", "address": ["172.19.0.1/30"], "mtu": 1400, "auto_route": true, "strict_route": true, "stack": "system" },
    { "type": "mixed", "tag": "socks-in", "listen": "127.0.0.1", "listen_port": 2080 }
  ],
  "outbounds": [
    $OUTBOUNDS
  ],
  "route": {
    "rules": [
      { "action": "sniff" },
      { "protocol": "dns", "action": "hijack-dns" },
      { "ip_is_private": true, "outbound": "direct" }
    ],
    "final": "$FINAL",
    "auto_detect_interface": true,
    "default_domain_resolver": "direct-dns"
  }
}
JSON
if "$SB" check -c "$CFG" 2>/tmp/sb-check.err; then
  [ -x /etc/init.d/sing-box ] && /etc/init.d/sing-box restart 2>/dev/null
  sleep 6
  # MUST silence stdout too: on fw4/iptables-nft routers postup's iptables commands
  # print rule lines, which would otherwise pollute this script's output and make
  # callers that read the first line (panel addserver/delserver) misread "OK".
  sh "$SBDIR/postup.sh" >/dev/null 2>&1
  echo OK
elif [ ! -s /tmp/sb-check.err ]; then
  # `sing-box check` returned non-zero but wrote NO error output -> it didn't actually
  # validate: on a RAM-starved router the ~58MB binary gets OOM-killed ("Terminated")
  # the moment it execs, with empty stderr. A real schema rejection always prints the
  # offending field. Our config is generated by parse-link.sh + this script (and checks
  # fine on a non-starved box), so don't discard a valid config just because the
  # validator couldn't run here — keep it and let the service validate at start.
  [ -x /etc/init.d/sing-box ] && /etc/init.d/sing-box restart 2>/dev/null
  sleep 6
  sh "$SBDIR/postup.sh" >/dev/null 2>&1
  echo OK
else
  cp -f "$CFG.bak" "$CFG" 2>/dev/null
  [ -x /etc/init.d/sing-box ] && /etc/init.d/sing-box restart 2>/dev/null
  echo "CHECK_FAIL"; head -5 /tmp/sb-check.err 2>/dev/null
fi
